# Generated by Django 5.0 on 2023-12-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activee',
            new_name='active',
        ),
    ]
